name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

env:
  HUGO_ENV: production
  HUGO_VERSION: "0.118.2"
  GO_VERSION: "1.20.5"
  NODE_VERSION: "18.15.0"

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Install Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-arm64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install Go
        run: |
          wget -O ${{ runner.temp }}/go.deb https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz \
          && sudo tar -C /usr/local -xzf ${{ runner.temp }}/go.deb

      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Setup Project
        run: npm run project-setup

      - name: Install npm dependencies
        run: npm install

      - name: Determine Base URL
        id: base_url
        run: |
          if [[ "${{ github.repository_owner }}.github.io" == "open-neuromorphic.github.io" ]]; then
            BASE_URL="https://open-neuromorphic.org/"
          else
            REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
            if [[ "${{ github.repository_owner }}" == "${{ github.repository_owner }}" ]]; then
              BASE_URL="https://${{ github.repository_owner }}.github.io/${REPO_NAME}/"
            else
              BASE_URL="https://${{ github.repository_owner }}.github.io/"
            fi
          fi
          echo "BASE_URL=$BASE_URL" >> $GITHUB_ENV

      - name: Modify hugo.toml
        run: sed -i "s|baseURL = .*|baseURL = \"$BASE_URL\"|" hugo.toml


      - name: Build site
        run: npm run build

      - name: Modify .htaccess (Prevent Indexing)
        run: |
          if [[ "$BASE_URL" != "https://open-neuromorphic.org/" ]]; then
            echo "Header set X-Robots-Tag \"noindex, nofollow\"" >> public/.htaccess
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04-arm
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
